<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="US3B7Z2PF6" failures="1" tests="4" name="Test" time="12.911" errors="0" timestamp="2025-07-09T15:59:36 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="5.92"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="1.545"/>
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="2.963"/>
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="1.487">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUser(UserTests.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- Test -->
